### ISSUE TITLE
MyPage 관련 과제들 

### ISSUE THREAD

**Issue by daisythepotato** [sdp-tech/UPCY_Mobile#144]
## Description
- reformer와 customer 역할에 따라 MyPage 탭 구성을 다르게 표시합니다.

## To-Do
- [x] 탭 구성 분리 및 getuserRole() 로 내용 가져오기
- [x] user nickname 여부에 따라 리폼러 프로필 등록 여부 파악 및 컴포넌트 렌더링
- [ ] customer 탭 UI 수정
- [x] reformer 탭 UI 수정
- [x] 수정 아이콘 변경
- [x] 로그아웃, 계정탈퇴 모달 만들기
- [x] 계정탈퇴 api 연결하기 
- [x] 프로필 수정 페이지 유저롤에 따라 다르게 렌더링하기 
- [x] 유저롤에 따라 다른 api 연결
- [ ] InfoPage api 연결하기
