### ISSUE TITLE
기본 컴포넌트 구현

### ISSUE THREAD

**Issue by eujin-shin** [sdp-tech/UPCY_Mobile#77]
## Description
- 하위 단계의 공통 컴포넌트 추가 및 리팩토링

## To-Do
- [ ] 드롭다운 UI 수정
- [ ] 마이페이지 컴포넌트 설계
- [ ] 룩북 컴포넌트 설계
