### ISSUE TITLE
스플래쉬 화면 구현

### ISSUE THREAD

**Issue by eujin-shin** [sdp-tech/UPCY_Mobile#83]
## Description
로고 애니메이션 포함 첫 화면 구현

## To-Do
- [ ] json 애니메이션 변환
- [ ] 로고 이동 애니메이션 구현
- [ ] 로그인 화면으로 네비게이팅

## ETC
Lottie 활용 예정
